### ISSUE TITLE
Allow user-defined pixel ratios

### ISSUE THREAD

**Issue by ruscur** [ertug/autohidpi#2]
Hey, thanks for making this addon, it's really useful.

It'd be nice to be able to define my own pixel ratio, 1.5x and 2x are both too large for my needs.

**Comment by mschulkind** [comment]
I second this request. Why not just make this a number input? I need something like 1.7 and other people will want yet another value.

I have a 163dpi screen, but firefox on linux renders like the screen is 96dpi, hence the 1.7x that I need.

**Comment by carlesso** [comment]
@mschulkind the problem is that you cannot enter a float number (at least using `simple-prefs`).

I've done a pull request (#6) which allows you to add a custom value 100 based, like if you want a 1.75 zoom, you just enter 175.

Let's see if @ertug can merge this, but if you need it bad, you can go to my fork, download and generate the xpi (or let me know and I'll upload it somewhere)

**Comment by ertug** [comment]
Thanks for the comments, its implemented.

You can use 1.2 (not reviewed yet):
https://addons.mozilla.org/en-US/firefox/addon/autohidpi/versions/1.2
